#!/bin/bash
# Regenerates src/fontIds.h. Redirect stdout to that file:
#   ./build-font-ids.sh > ../../../src/fontIds.h

set -e

cd "$(dirname "$0")/../builtinFonts"

python3 - <<'EOF'
import hashlib

def font_id(*paths):
    total = sum(int(hashlib.sha256(open(p, 'rb').read()).hexdigest(), 16) for p in paths)
    return total % (2 ** 32) - (2 ** 31)

def four(prefix, size):
    s = str(size)
    return font_id(
        f"./{prefix}_{s}_regular.h",
        f"./{prefix}_{s}_bold.h",
        f"./{prefix}_{s}_italic.h",
        f"./{prefix}_{s}_bolditalic.h",
    )

print("// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.sh")
print("#pragma once")
print("")

for size in [11, 12, 14, 18]:
    print(f"#define BOOKERLY_{size}_FONT_ID ({four('bookerly', size)})")

print("")

for size in [12, 13, 15, 19]:
    print(f"#define NEWSREADER_{size}_FONT_ID ({four('newsreader', size)})")

print("")

for size in [12, 13, 15, 19]:
    print(f"#define CHAREINK_{size}_FONT_ID ({four('chareink', size)})")

print("")

print(f"#define UI_10_FONT_ID ({font_id('./ubuntu_10_regular.h', './ubuntu_10_bold.h')})")
print(f"#define UI_12_FONT_ID ({font_id('./ubuntu_12_regular.h', './ubuntu_12_bold.h')})")
print(f"#define SMALL_FONT_ID ({font_id('./notosans_8_regular.h')})")
EOF
