#!/usr/bin/env python3
"""
Font pipeline automation — reads fonts.json and updates four source files:

  lib/EpdFont/builtinFonts/all.h       — reader font #include block
  src/fontIds.h                         — font ID #defines (fully rewritten)
  src/main.cpp                          — EpdFont/EpdFontFamily decls + insertFont calls
  src/CrossPointSettings.cpp            — getReaderFontId() switch body

Usage (from the scripts/ directory):
  python3 sync-fonts.py           # generate font .h files then update sources
  python3 sync-fonts.py --no-gen  # skip font generation, just update sources
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, "../../.."))
CONFIG_PATH = os.path.join(SCRIPT_DIR, "fonts.json")
BUILTIN_DIR = os.path.normpath(os.path.join(SCRIPT_DIR, "../builtinFonts"))

ALL_H_PATH          = os.path.join(BUILTIN_DIR, "all.h")
FONT_IDS_PATH       = os.path.join(REPO_ROOT, "src/fontIds.h")
MAIN_CPP_PATH       = os.path.join(REPO_ROOT, "src/main.cpp")
SETTINGS_CPP_PATH   = os.path.join(REPO_ROOT, "src/CrossPointSettings.cpp")

STYLE_ORDER = ["regular", "bold", "italic", "bolditalic"]
TIER_ENUMS  = ["TINY", "SMALL", "MEDIUM", "EXTRA_LARGE"]
FONT_SIZE_COUNT = 4


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def size_to_name(s: float) -> str:
    """11 → '11', 11.5 → '11_5'"""
    if s == int(s):
        return str(int(s))
    return f"{s:.1f}".replace(".", "_")


def camel(name: str, size: float) -> str:
    """bookerly, 11.5 → 'bookerly11_5'"""
    return f"{name}{size_to_name(size)}"


def font_id_from_files(*paths: str) -> int:
    total = 0
    for p in paths:
        with open(p, "rb") as f:
            total += int(hashlib.sha256(f.read()).hexdigest(), 16)
    return total % (2 ** 32) - (2 ** 31)


def macro_name(font_name: str, size: float) -> str:
    """bookerly, 14 → 'BOOKERLY_14_FONT_ID'"""
    return f"{font_name.upper()}_{size_to_name(size)}_FONT_ID"


def replace_between_markers(text: str, open_marker: str, close_marker: str, new_content: str) -> str:
    """Replace everything between open_marker line and close_marker line (exclusive)."""
    pattern = re.compile(
        r'([ \t]*' + re.escape(open_marker) + r'[ \t]*\n)'
        r'.*?'
        r'([ \t]*' + re.escape(close_marker) + r'[ \t]*)',
        re.DOTALL,
    )
    replacement = r'\g<1>' + new_content + r'\g<2>'
    result, count = pattern.subn(replacement, text)
    if count == 0:
        sys.exit(f"ERROR: marker pair '{open_marker}' / '{close_marker}' not found")
    return result


def read_file(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def write_file(path: str, content: str) -> None:
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"  updated: {os.path.relpath(path, REPO_ROOT)}")


# ---------------------------------------------------------------------------
# Load config
# ---------------------------------------------------------------------------

def load_config():
    with open(CONFIG_PATH) as f:
        config = json.load(f)
    fonts = config["fonts"]

    # Validate that every reader font has exactly FONT_SIZE_COUNT sizes
    for font in fonts:
        n = len(font["sizes"])
        if n != FONT_SIZE_COUNT:
            sys.exit(
                f"ERROR: font '{font['name']}' has {n} sizes, expected {FONT_SIZE_COUNT}"
            )
    return fonts


# ---------------------------------------------------------------------------
# all.h — reader font #include block
# ---------------------------------------------------------------------------

def gen_all_h_block(fonts) -> str:
    lines = []
    for font in fonts:
        name = font["name"]
        for size_entry in font["sizes"]:
            sz = size_entry["size"]
            sn = size_to_name(sz)
            for style in STYLE_ORDER:
                lines.append(f'#include <builtinFonts/{name}_{sn}_{style}.h>')
    return "\n".join(lines) + "\n"


def update_all_h(fonts) -> None:
    text = read_file(ALL_H_PATH)
    text = replace_between_markers(text, "// <<< GENERATED", "// GENERATED >>>", gen_all_h_block(fonts))
    write_file(ALL_H_PATH, text)


# ---------------------------------------------------------------------------
# fontIds.h — fully rewritten
# ---------------------------------------------------------------------------

def gen_font_ids(fonts) -> str:
    lines = [
        "// The contents of this file are generated by ./lib/EpdFont/scripts/sync-fonts.py",
        "#pragma once",
        "",
    ]
    for font in fonts:
        name = font["name"]
        for size_entry in font["sizes"]:
            sz = size_entry["size"]
            sn = size_to_name(sz)
            file_paths = [
                os.path.join(BUILTIN_DIR, f"{name}_{sn}_{style}.h")
                for style in STYLE_ORDER
            ]
            fid = font_id_from_files(*file_paths)
            lines.append(f"#define {macro_name(name, sz)} ({fid})")
        lines.append("")

    lines.append(f"#define UI_10_FONT_ID ({font_id_from_files(os.path.join(BUILTIN_DIR, 'ubuntu_10_regular.h'), os.path.join(BUILTIN_DIR, 'ubuntu_10_bold.h'))})")
    lines.append(f"#define UI_12_FONT_ID ({font_id_from_files(os.path.join(BUILTIN_DIR, 'ubuntu_12_regular.h'), os.path.join(BUILTIN_DIR, 'ubuntu_12_bold.h'))})")
    lines.append(f"#define SMALL_FONT_ID ({font_id_from_files(os.path.join(BUILTIN_DIR, 'notosans_8_regular.h'))})")
    lines.append("")
    return "\n".join(lines)


def update_font_ids(fonts) -> None:
    write_file(FONT_IDS_PATH, gen_font_ids(fonts))


# ---------------------------------------------------------------------------
# main.cpp — two marker pairs
# ---------------------------------------------------------------------------

def gen_main_decls(fonts) -> str:
    """Content between FONT DECLS markers.

    Structure mirrors existing code:
      - default font (index 2 = FONT_L) declared outside #ifndef OMIT_FONTS
      - remaining sizes + all other fonts inside #ifndef OMIT_FONTS
    """
    lines = []

    for fi, font in enumerate(fonts):
        name = font["name"]
        sizes = [e["size"] for e in font["sizes"]]
        default_sz = sizes[2]  # FONT_L is the default

        if fi == 0:
            # First font: default size outside guard, rest inside
            _append_family_decl(lines, name, default_sz)
            lines.append("#ifndef OMIT_FONTS")
            for sz in sizes:
                if sz != default_sz:
                    _append_family_decl(lines, name, sz)
        else:
            lines.append("")
            for sz in sizes:
                _append_family_decl(lines, name, sz)

    lines.append("#endif  // OMIT_FONTS")
    return "\n".join(lines) + "\n"


def _append_family_decl(lines, name, sz):
    c = camel(name, sz)
    sn = size_to_name(sz)
    # Align the EpdFontFamily continuation line to column 0 padding matching existing style
    # We use the variable name length to compute padding, mimicking existing hand-written alignment.
    family_var = f"{c}FontFamily"
    indent = " " * (len("EpdFontFamily ") + len(family_var) + len("("))
    lines.append(f"EpdFont {c}RegularFont(&{name}_{sn}_regular);")
    lines.append(f"EpdFont {c}BoldFont(&{name}_{sn}_bold);")
    lines.append(f"EpdFont {c}ItalicFont(&{name}_{sn}_italic);")
    lines.append(f"EpdFont {c}BoldItalicFont(&{name}_{sn}_bolditalic);")
    lines.append(f"EpdFontFamily {family_var}(&{c}RegularFont, &{c}BoldFont,")
    lines.append(f"{indent}&{c}ItalicFont, &{c}BoldItalicFont);")


def gen_main_inserts(fonts) -> str:
    """Content between FONT INSERTS markers.

    Same guard structure: default font outside #ifndef, others inside.
    """
    lines = []

    for fi, font in enumerate(fonts):
        name = font["name"]
        sizes = [e["size"] for e in font["sizes"]]
        default_sz = sizes[2]  # FONT_L

        if fi == 0:
            c = camel(name, default_sz)
            lines.append(f"  renderer.insertFont({macro_name(name, default_sz)}, {c}FontFamily);")
            lines.append("#ifndef OMIT_FONTS")
            for sz in sizes:
                if sz != default_sz:
                    c2 = camel(name, sz)
                    lines.append(f"  renderer.insertFont({macro_name(name, sz)}, {c2}FontFamily);")
            lines.append("")
        else:
            for sz in sizes:
                c = camel(name, sz)
                lines.append(f"  renderer.insertFont({macro_name(name, sz)}, {c}FontFamily);")

    lines.append("#endif  // OMIT_FONTS")
    return "\n".join(lines) + "\n"


def update_main_cpp(fonts) -> None:
    text = read_file(MAIN_CPP_PATH)
    text = replace_between_markers(text, "// <<< GENERATED FONT DECLS", "// GENERATED FONT DECLS >>>", gen_main_decls(fonts))
    text = replace_between_markers(text, "// <<< GENERATED FONT INSERTS", "// GENERATED FONT INSERTS >>>", gen_main_inserts(fonts))
    write_file(MAIN_CPP_PATH, text)


# ---------------------------------------------------------------------------
# CrossPointSettings.cpp — getFontId() switch body
# ---------------------------------------------------------------------------

def gen_settings_switch(fonts) -> str:
    lines = ["  switch (f) {"]
    for fi, font in enumerate(fonts):
        name = font["name"]
        sizes = [e["size"] for e in font["sizes"]]
        enum_name = name.upper()

        if fi == 0:
            lines.append(f"    case {enum_name}:")
            lines.append(f"    default:")
        else:
            lines.append(f"    case {enum_name}:")

        lines.append(f"      switch (s) {{")
        for ti, (tier, sz) in enumerate(zip(TIER_ENUMS, sizes)):
            mid = macro_name(name, sz)
            is_default = (ti == 2)  # FONT_L
            if is_default:
                lines.append(f"        case {tier}:")
                lines.append(f"        default:")
                lines.append(f"          return {mid};")
            else:
                lines.append(f"        case {tier}:")
                lines.append(f"          return {mid};")
        lines.append(f"      }}")

    lines.append(f"  }}")
    return "\n".join(lines) + "\n"


def update_settings_cpp(fonts) -> None:
    text = read_file(SETTINGS_CPP_PATH)
    text = replace_between_markers(text, "// <<< GENERATED", "// GENERATED >>>", gen_settings_switch(fonts))
    write_file(SETTINGS_CPP_PATH, text)


# ---------------------------------------------------------------------------
# Font generation
# ---------------------------------------------------------------------------

def run_font_generation() -> None:
    convert_script = os.path.join(SCRIPT_DIR, "convert-fonts.py")
    print("Running convert-fonts.py ...")
    result = subprocess.run(
        [sys.executable, convert_script],
        cwd=SCRIPT_DIR,
    )
    if result.returncode != 0:
        sys.exit(f"ERROR: convert-fonts.py failed (exit {result.returncode})")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--no-gen", action="store_true", help="Skip font generation step.")
    args = ap.parse_args()

    fonts = load_config()
    print(f"Loaded {len(fonts)} font families from fonts.json")

    if not args.no_gen:
        run_font_generation()

    print("Updating source files ...")
    update_all_h(fonts)
    update_font_ids(fonts)
    update_main_cpp(fonts)
    update_settings_cpp(fonts)
    print("Done.")


if __name__ == "__main__":
    main()
