#pragma once

#include <builtinFonts/bookerly_11_bold.h>
#include <builtinFonts/bookerly_11_bolditalic.h>
#include <builtinFonts/bookerly_11_italic.h>
#include <builtinFonts/bookerly_11_regular.h>
#include <builtinFonts/bookerly_12_bold.h>
#include <builtinFonts/bookerly_12_bolditalic.h>
#include <builtinFonts/bookerly_12_italic.h>
#include <builtinFonts/bookerly_12_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_bolditalic.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_18_bold.h>
#include <builtinFonts/bookerly_18_bolditalic.h>
#include <builtinFonts/bookerly_18_italic.h>
#include <builtinFonts/bookerly_18_regular.h>
#include <builtinFonts/chareink_12_bold.h>
#include <builtinFonts/chareink_12_bolditalic.h>
#include <builtinFonts/chareink_12_italic.h>
#include <builtinFonts/chareink_12_regular.h>
#include <builtinFonts/chareink_13_bold.h>
#include <builtinFonts/chareink_13_bolditalic.h>
#include <builtinFonts/chareink_13_italic.h>
#include <builtinFonts/chareink_13_regular.h>
#include <builtinFonts/chareink_15_bold.h>
#include <builtinFonts/chareink_15_bolditalic.h>
#include <builtinFonts/chareink_15_italic.h>
#include <builtinFonts/chareink_15_regular.h>
#include <builtinFonts/chareink_19_bold.h>
#include <builtinFonts/chareink_19_bolditalic.h>
#include <builtinFonts/chareink_19_italic.h>
#include <builtinFonts/chareink_19_regular.h>
#include <builtinFonts/newsreader_12_bold.h>
#include <builtinFonts/newsreader_12_bolditalic.h>
#include <builtinFonts/newsreader_12_italic.h>
#include <builtinFonts/newsreader_12_regular.h>
#include <builtinFonts/newsreader_13_bold.h>
#include <builtinFonts/newsreader_13_bolditalic.h>
#include <builtinFonts/newsreader_13_italic.h>
#include <builtinFonts/newsreader_13_regular.h>
#include <builtinFonts/newsreader_15_bold.h>
#include <builtinFonts/newsreader_15_bolditalic.h>
#include <builtinFonts/newsreader_15_italic.h>
#include <builtinFonts/newsreader_15_regular.h>
#include <builtinFonts/newsreader_19_bold.h>
#include <builtinFonts/newsreader_19_bolditalic.h>
#include <builtinFonts/newsreader_19_italic.h>
#include <builtinFonts/newsreader_19_regular.h>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
