#pragma once

// <<< GENERATED
#include <builtinFonts/bookerly_10_regular.h>
#include <builtinFonts/bookerly_10_bold.h>
#include <builtinFonts/bookerly_10_italic.h>
#include <builtinFonts/bookerly_10_bolditalic.h>
#include <builtinFonts/bookerly_11_regular.h>
#include <builtinFonts/bookerly_11_bold.h>
#include <builtinFonts/bookerly_11_italic.h>
#include <builtinFonts/bookerly_11_bolditalic.h>
#include <builtinFonts/bookerly_14_regular.h>
#include <builtinFonts/bookerly_14_bold.h>
#include <builtinFonts/bookerly_14_italic.h>
#include <builtinFonts/bookerly_14_bolditalic.h>
#include <builtinFonts/bookerly_17_regular.h>
#include <builtinFonts/bookerly_17_bold.h>
#include <builtinFonts/bookerly_17_italic.h>
#include <builtinFonts/bookerly_17_bolditalic.h>
#include <builtinFonts/chareink_11_regular.h>
#include <builtinFonts/chareink_11_bold.h>
#include <builtinFonts/chareink_11_italic.h>
#include <builtinFonts/chareink_11_bolditalic.h>
#include <builtinFonts/chareink_11_5_regular.h>
#include <builtinFonts/chareink_11_5_bold.h>
#include <builtinFonts/chareink_11_5_italic.h>
#include <builtinFonts/chareink_11_5_bolditalic.h>
#include <builtinFonts/chareink_16_regular.h>
#include <builtinFonts/chareink_16_bold.h>
#include <builtinFonts/chareink_16_italic.h>
#include <builtinFonts/chareink_16_bolditalic.h>
#include <builtinFonts/chareink_19_regular.h>
#include <builtinFonts/chareink_19_bold.h>
#include <builtinFonts/chareink_19_italic.h>
#include <builtinFonts/chareink_19_bolditalic.h>
#include <builtinFonts/newsreader_11_7_regular.h>
#include <builtinFonts/newsreader_11_7_bold.h>
#include <builtinFonts/newsreader_11_7_italic.h>
#include <builtinFonts/newsreader_11_7_bolditalic.h>
#include <builtinFonts/newsreader_12_2_regular.h>
#include <builtinFonts/newsreader_12_2_bold.h>
#include <builtinFonts/newsreader_12_2_italic.h>
#include <builtinFonts/newsreader_12_2_bolditalic.h>
#include <builtinFonts/newsreader_16_regular.h>
#include <builtinFonts/newsreader_16_bold.h>
#include <builtinFonts/newsreader_16_italic.h>
#include <builtinFonts/newsreader_16_bolditalic.h>
#include <builtinFonts/newsreader_19_regular.h>
#include <builtinFonts/newsreader_19_bold.h>
#include <builtinFonts/newsreader_19_italic.h>
#include <builtinFonts/newsreader_19_bolditalic.h>
// GENERATED >>>
#include <builtinFonts/notosans_8_regular.h>
#include <builtinFonts/notosans_12_bold.h>
#include <builtinFonts/notosans_12_bolditalic.h>
#include <builtinFonts/notosans_12_italic.h>
#include <builtinFonts/notosans_12_regular.h>
#include <builtinFonts/notosans_14_bold.h>
#include <builtinFonts/notosans_14_bolditalic.h>
#include <builtinFonts/notosans_14_italic.h>
#include <builtinFonts/notosans_14_regular.h>
#include <builtinFonts/notosans_16_bold.h>
#include <builtinFonts/notosans_16_bolditalic.h>
#include <builtinFonts/notosans_16_italic.h>
#include <builtinFonts/notosans_16_regular.h>
#include <builtinFonts/notosans_18_bold.h>
#include <builtinFonts/notosans_18_bolditalic.h>
#include <builtinFonts/notosans_18_italic.h>
#include <builtinFonts/notosans_18_regular.h>
#include <builtinFonts/ubuntu_10_bold.h>
#include <builtinFonts/ubuntu_10_regular.h>
#include <builtinFonts/ubuntu_12_bold.h>
#include <builtinFonts/ubuntu_12_regular.h>
